version: '3.2'
services:
  multiple-todo-list-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "multiple-todo-list-db-data:/var/lib/postgresql/data"

volumes:
  multiple-todo-list-db-data: